# Generated by Django 5.1.5 on 2025-01-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_consumed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operating_hours_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField()),
                ('power_produced', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('power_rating', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('power_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('phase1_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase2_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase3_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase1_current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase2_current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase3_current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frequency', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('power_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_power', to='e_app.powersource')),
            ],
        ),
    ]
