# Generated by Django 5.1.5 on 2025-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptiondata',
            name='power_consumed',
        ),
        migrations.AddField(
            model_name='consumptiondata',
            name='number_of_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
