# Generated by Django 5.1.5 on 2025-01-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0002_remove_consumptiondata_power_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptiondata',
            name='power_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
