# Generated by Django 5.1.5 on 2025-01-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_consumptiondata_power_consumed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powersource',
            old_name='power_produced',
            new_name='power_supplied',
        ),
        migrations.RemoveField(
            model_name='consumptiondata',
            name='phase1_current',
        ),
        migrations.RemoveField(
            model_name='consumptiondata',
            name='phase1_voltage',
        ),
        migrations.RemoveField(
            model_name='consumptiondata',
            name='phase2_current',
        ),
        migrations.RemoveField(
            model_name='consumptiondata',
            name='phase2_voltage',
        ),
        migrations.RemoveField(
            model_name='consumptiondata',
            name='phase3_current',
        ),
        migrations.RemoveField(
            model_name='consumptiondata',
            name='phase3_voltage',
        ),
    ]
