# Generated by Django 5.1.5 on 2025-01-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_rename_power_produced_powersource_power_supplied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='power_consumed',
            new_name='power_rating',
        ),
        migrations.RemoveField(
            model_name='consumptiondata',
            name='number_of_hours',
        ),
    ]
