# Generated by Django 5.1.5 on 2025-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0006_alter_consumptiondata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptiondata',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consumptiondata',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
