# Generated by Django 5.1.5 on 2025-01-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0007_alter_consumptiondata_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersource',
            name='power_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
