# Generated by Django 5.1.5 on 2025-02-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(max_length=100),
        ),
    ]
